project:
  type: website
  output-dir: docs

website:
  title: "C. Blain Morin"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

